applicationset:
  apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: myapp-applicationset
    namespace: gowri
    uid: af194e95-bac7-43e9-abf0-648811ab4b0e
    resourceVersion: null
    generation: null
    creationTimestamp: 2025-11-12T00:19:08Z
    managedFields:
      - manager: argocd-applicationset-controller
        operation: Update
        apiVersion: argoproj.io/v1alpha1
        time: 2025-11-12T00:19:17Z
        fieldsType: FieldsV1
        fieldsV1:
          f:status:
            .: {}
            f:conditions: {}
        subresource: status
      - manager: agent
        operation: Update
        apiVersion: argoproj.io/v1alpha1
        time: 2025-11-12T00:22:17Z
        fieldsType: FieldsV1
        fieldsV1:
          f:spec:
            .: {}
            f:generators: {}
            f:goTemplate: {}
            f:goTemplateOptions: {}
            f:template:
              .: {}
              f:metadata:
                .: {}
                f:name: {}
              f:spec:
                .: {}
                f:destination:
                  .: {}
                  f:namespace: {}
                  f:server: {}
                f:project: {}
                f:source:
                  .: {}
                  f:path: {}
                  f:repoURL: {}
                  f:targetRevision: {}
                f:syncPolicy:
                  .: {}
                  f:automated:
                    .: {}
                    f:prune: {}
                    f:selfHeal: {}
  spec:
    generators:
      - list:
          elements:
            - cluster: https://kubernetes.default.svc
              env: dev
            - cluster: https://prod.cluster.example.com
              env: prod-2
          template:
            metadata: {}
            spec:
              destination: {}
    goTemplate: true
    goTemplateOptions:
      - missingkey=error
    template:
      metadata:
        name: "{{env}}-myapp"
      spec:
        source:
          repoURL: https://github.com/gowrisgirish/Gitops-Samples.git
          path: ApplicationSet-Sample/apps/guestbook/
          targetRevision: main
        destination:
          server: "{{cluster}}"
          namespace: gowri
        project: e5cf5edd
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions: []
